<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="NuevaCompra.aspx.cs" Inherits="WebApp.NuevaCompra" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">



</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    <script>
        function validar() {
            var precio = $('#txtPrecio').val();
            var cantidad = $('#txtCantidad').val();
            
            if (!precio || !cantidad)
            {
                 alert('Debes completar todos los campos para proceder!');
                 return false;

             }
             if (isNaN(precio.replace(",",".")))
             {
                 alert('El campo "Precio" debe contener un numero!');
                 return false;
             }
             if (isNaN(cantidad) || cantidad % 1 !== 0)
             {
                 alert('El campo "Cantidad" debe contener un numero entero!');
                 return false;
             }
            return true;
            }
    </script>
 
            <table class="table" style="text-align:center">
                <thead class="thead-light">
                <tr>
                    <th colspan="3" >
                        <label style="margin:0px 15px 10px 15px">Proveedor</label>
                        <asp:DropDownList  style="width:300px" ID="ddlProveedores" AutoPostBack="true" OnSelectedIndexChanged="ddlProveedores_OnSelectedIndexChanged" runat="server"></asp:DropDownList>
                    </th>
                </tr>
                </thead>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <label>Producto</label>
                        <asp:DropDownList ID="ddlProductos"  runat="server"> </asp:DropDownList>
                    </td>
                    <td>
                        <label>Precio </label>
                        <asp:TextBox BackColor= "WhiteSmoke" runat="server" ClientIDMode="Static" ID="txtPrecio" />
                    </td>
                    <td>
                        <label>Cantidad </label>
                        <asp:TextBox BackColor= "WhiteSmoke" runat="server" ClientIDMode="Static" ID="txtCantidad" />
                    </td>
                </tr>
                <tr>
                    <td colspan="3" style="text-align:center">
                        <asp:Button Text="Agregar Detalle" style="margin-right:10px" OnClientClick="return validar()" CssClass ="btn btn-secondary" OnClick="AgregarDetalle" runat="server" />
                        <asp:Button Text="Guardar Compra" style="margin-left:10px" CssClass ="btn btn-secondary" OnClick="GuardarCompra" runat="server" />
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                         <label>Importe Total: <%--$<%=Session["totalDetalle"] != null? (float)Session["totalDetalle"] : 0%>--%></label>
                        <asp:TextBox ReadOnly="true" BackColor= "LightGray" runat="server" ID="txtTotal" />
                    </td>
                </tr>
            </table>

            <asp:GridView CssClass="table table-dark" ID="dgvDetalleCompra" runat="server"  OnRowDeleting="RowDeleting" OnRowDeleted="RowDeleted" AutoGenerateDeleteButton="false" AutoGenerateColumns="false">
                        <Columns>    
                            <asp:BoundField DataField="Producto.ID" HeaderText="ID" Visible="true"/>
                            <asp:BoundField DataField="Producto.Titulo" HeaderText="Producto" />
                            <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" />
                            <asp:BoundField DataFormatString="{0:C}" DataField="Precio" HeaderText="Precio Unitario" />
                            <asp:BoundField DataFormatString="{0:C}" DataField="SubTotal" HeaderText="Sub Total" />
                            <asp:CommandField ButtonType="Image" ItemStyle-Height="10px"  DeleteImageUrl="~/img/x-button.svg.hi.png" ShowDeleteButton="True" />
                        </Columns>  
             </asp:GridView>



     
 
  
</asp:Content>
